<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15_SelectProvideCar</name>
   <tag></tag>
   <elementGuidId>ba319e68-3ccd-4b53-b231-8a4bdcef407b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[contains(text(),'${ProvideCar}')]/parent::div/parent::div/parent::div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
