<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16_SelectLokasiPengambilan</name>
   <tag></tag>
   <elementGuidId>7299b9c6-06a8-4c10-a5fa-24ecb319a8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@tabindex='0']//div[contains(text(),'${TypeLokasiPengambilan}')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
