<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18_SelectDrpDwnLokasiPengambilan</name>
   <tag></tag>
   <elementGuidId>af81a31f-7319-4438-a3e3-2d0e792ad8f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@tabindex='0']//div[contains(text(),'${SelectLokasiPengambilan}')])[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
